Dataset:
# Dasaset parameters, discuss it with Dasha


Image Encoder:
  model: "resnet50"
  embedding_size: 2048
  pretrained: True
  trainable: False

Text Encoder:
  model: "ai-forever/sbert_large_nlu_ru"
  embedding_size: 768
  max_length: 512
  pretrained: True
  trainable: False

Connector:
  connectors: 1
  connector_size: 256
  dropout: 0.1

Train parameters:
  batch_size: 5
  epochs: 100
  learning_rate: 0.001
  gamma: 0.8
  num_workers: 0
  t_prime: 10.0
  bias: -10.0
  seed: 42
  save_model: True
