Dataset:
# Dasaset parameters, discuss it with Dasha


Image Encoder:
  model: "resnet50"
  embedding_size: 2048
  pretrained: True
  trainable: False

Text Encoder:
  model: "google-bert/bert-base-multilingual-cased"
  embedding_size: 768
  max_length: 64
  pretrained: True
  trainable: False

Connector:
  connectors: 1
  connector_size: 256
  dropout: 0.1

Train parameters:
  batch_size: 50
  epochs: 100
  learning_rate: 0.001
  gamma: 0.9
  num_workers: 0
  temperature: 10.0
  bias: -10.0
  seed: 42
  save_model: False
