Model parameters:
  image_encoder_params:
    model_name: "resnet50"
    pretrained: True
    freeze: True
  text_encoder_params:
    model_name: "google-bert/bert-base-multilingual-cased"
    pretrained: True
    freeze: True
  connector_params:
    connectors: 1
    connector_size: 256
    dropout: 0.1
  image_embedding_size: 2048
  text_embedding_size: 768

Train dataset name: "WikiDataset"
Train dataset parameters:
  dataset_directory: "datasets/wiki_dataset/"
  tokenizer_name: "google-bert/bert-base-multilingual-cased"
  load_tokenized_files: False
  save_tokenized_files: True
  max_sequence_length: 64

Test dataset name: "LaionCocoDataset"
Test dataset parameters:
  dataset_directory: "datasets/laion_coco_dataset/"
  tokenizer_name: "google-bert/bert-base-multilingual-cased"
  load_tokenized_files: False
  save_tokenized_files: True
  max_sequence_length: 64

Dataloader parameters:
  batch_size: 250
  seed: 42

Loss parameters:
  temperature: 10.0
  bias: -10.0

Optimizer parameters:
  lr: 0.001

Scheduler parameters:
  step_size: 10
  gamma: 0.9

Train parameters:
  epochs: 100
  save_model: False
  save_directory: "trained_models/model01.pt"
