name: rusiglip
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
  - huggingface
  - menpo
  - mosaicml
dependencies:
  - accelerate
  - albumentations
  - deepspeed
  - mosaicml
  - numpy
  - opencv
  - pillow
  - pip
  - python=3.11
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - safetensors
  - tqdm
  - transformers
  - wandb
  - pip:
      - aiogram
      - aiosqlite
      - pytest

